# Multilinear Regression

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [1]:
import pandas as pd
dataset = pd.read_csv(r"C:\Users\Neha reddy\OneDrive\Documents\table_files\50_Startups.csv")

In [2]:
dataset.isnull().any()

R&D Spend          False
Administration      True
Marketing Spend     True
State              False
Profit             False
dtype: bool

In [3]:
dataset["Administration"].fillna(dataset["Administration"].mean(),inplace = True)
dataset["Marketing Spend"].fillna(dataset["Marketing Spend"].mean(),inplace = True)


In [4]:
dataset.isnull().any()

R&D Spend          False
Administration     False
Marketing Spend    False
State              False
Profit             False
dtype: bool

In [5]:
dataset.describe()

R&D Spend  Administration  Marketing Spend         Profit
count      50.000000       50.000000        50.000000      50.000000
mean    73721.615600   121564.038163    212725.266735  112012.639200
std     45902.256482    27974.818762    121697.951409   40306.180338
min         0.000000    51283.140000         0.000000   14681.400000
25%     39936.370000   103730.875000    135028.207500   90138.902500
50%     73051.080000   122699.795000    213680.038367  107978.190000
75%    101602.800000   144842.180000    299469.085000  139765.977500
max    165349.200000   182645.560000    471784.100000  192261.830000

In [6]:
import seaborn as sns
sns.boxplot(dataset["Administration"])

In [7]:
x = dataset.iloc[:,0:4].values
y = dataset.iloc[:,4:5].values

In [8]:
x[0]

array([165349.2, 136897.8, 471784.1, 'New York'], dtype=object)

In [9]:
dataset["State"].unique()

array(['New York', 'California', 'Florida'], dtype=object)

In [10]:
x.shape

(50, 4)

In [11]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
from sklearn.pipeline import Pipeline

In [12]:
ct = ColumnTransformer([("oh",OneHotEncoder(),[3])],remainder = "passthrough")
x = ct.fit_transform(x)
x

array([[0.0, 0.0, 1.0, 165349.2, 136897.8, 471784.1],
       [1.0, 0.0, 0.0, 162597.7, 151377.59, 443898.53],
       [0.0, 1.0, 0.0, 153441.51, 101145.55, 407934.54],
       [0.0, 0.0, 1.0, 144372.41, 118671.85, 383199.62],
       [0.0, 1.0, 0.0, 142107.34, 91391.77, 366168.42],
       [0.0, 0.0, 1.0, 131876.9, 99814.71, 362861.36],
       [1.0, 0.0, 0.0, 134615.46, 147198.87, 212725.26673469393],
       [0.0, 1.0, 0.0, 130298.13, 145530.06, 323876.68],
       [0.0, 0.0, 1.0, 120542.52, 148718.95, 311613.29],
       [1.0, 0.0, 0.0, 123334.88, 108679.17, 304981.62],
       [0.0, 1.0, 0.0, 101913.08, 121564.03816326526, 229160.95],
       [1.0, 0.0, 0.0, 100671.96, 91790.61, 249744.55],
       [0.0, 1.0, 0.0, 93863.75, 127320.38, 249839.44],
       [1.0, 0.0, 0.0, 91992.39, 135495.07, 252664.93],
       [0.0, 1.0, 0.0, 119943.24, 156547.42, 256512.92],
       [0.0, 0.0, 1.0, 114523.61, 122616.84, 261776.23],
       [1.0, 0.0, 0.0, 78013.11, 121597.55, 264346.06],
       [0.0, 0.0, 1.0, 9

In [13]:
x.shape

(50, 6)

In [14]:
import joblib 
joblib.dump(ct,"column")

['column']

In [15]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size = 0.2,random_state = 0)

In [16]:
from sklearn.linear_model import LinearRegression
multilinear = LinearRegression()
multilinear.fit(x_train,y_train)


LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [17]:
y_pred = multilinear.predict(x_test)

In [18]:
y_pred

array([[102878.005919  ],
       [132270.25447715],
       [132633.73140008],
       [ 72126.02121903],
       [178331.5060337 ],
       [116426.57493052],
       [ 68171.67631542],
       [ 98737.3884056 ],
       [114057.16028013],
       [167719.48557509]])

In [19]:
y_test

array([[103282.38],
       [144259.4 ],
       [146121.95],
       [ 77798.83],
       [191050.39],
       [105008.31],
       [ 81229.06],
       [ 97483.56],
       [110352.25],
       [166187.94]])

In [20]:
from sklearn.metrics import r2_score
accuracy = r2_score(y_test,y_pred)

In [21]:
accuracy

0.9344508898504166

In [22]:
x.shape

(50, 6)

In [38]:
x[8]

array([0.0, 0.0, 1.0, 120542.52, 148718.95, 311613.29], dtype=object)

In [24]:
import pickle 
pickle.dump(multilinear,open('profit.pkl','wb'))

In [25]:
Newyork California Florida
California  Florida    Newyork
1            0           0
0            1           0
0           0             1



SyntaxError: invalid syntax (<ipython-input-25-aace5fb4bdee>, line 1)

In [26]:
yp = multilinear.predict([[1,0,0,12345,12345,3456]])

In [27]:
yp

array([[52470.96807743]])

In [28]:
new = joblib.load('column')

In [29]:
[[1645,2567,6787,"New york"]]

[[1645, 2567, 6787, 'New york']]

In [30]:
p = new.transform([[1645,2567,6787,"Florida"]])

In [31]:
p

array([[0.0, 1.0, 0.0, 1645, 2567, 6787]], dtype=object)

In [32]:
y1 = multilinear.predict(p)

In [33]:
y1

array([[43277.23627494]])

In [34]:
y2 = multilinear.predict(new.transform([[12345,56789,12345,"California"]]))

In [35]:
y2

array([[54267.44556097]])

In [36]:
y3 = multilinear.predict(new.transform([[1234567,4568987,2345,"New York"]]))

In [37]:
y3

array([[1141417.50251184]])